### ISSUE TITLE
Custom CSS on Firefox (linux) with Refined GitHub

### ISSUE THREAD

**Issue by kierun** [githubnext/monaspace#128]
I am using [Refined GitHub](https://github.com/refined-github/refined-github) and have this snipet as a custom CSS:

```css
/* optional, you can also just use system fonts. */
.react-code-text, .react-code-lines, pre, code, .blob-code, .blob-code-marker {
  font-family: "Monaspace Xenon", monospace !important;
  font-size: 14px;
}
pre.CodeMirror-line {
  font: inherit;
}
```

- On Chrome, this works fine. I get the Monaspace Xenon font. 
- On Firefox, no luck. I just get the default monospace font.

_What am I doing wrong?_
