### ISSUE TITLE
Problem with colored output in Alacritty

### ISSUE THREAD

**Issue by ambitious-octopus** [githubnext/monaspace#146]
I am using Alacritty (alacritty 0.12.2) and zsh, some colored output breaks the font.

`ls` command produce this: 
![image](https://github.com/githubnext/monaspace/assets/3855193/44324897-e52a-4d1d-9041-a550380787d0)

other commands, on the other hand, give no problems

![image](https://github.com/githubnext/monaspace/assets/3855193/c30f4401-6bfd-4ce3-9562-fc59ec3b231f)

others are instead mixed (see user column)

![image](https://github.com/githubnext/monaspace/assets/3855193/2ed8863b-6c98-491a-8489-23fcfe540bf8)

I think something bad happens with LS_COLORS, because by setting all colors to 0, the font is perfect!

![image](https://github.com/githubnext/monaspace/assets/3855193/13e849d7-afb7-4fa9-a37e-fea9d204f208)

Do you have any insight into this problem?

**Comment by ambitious-octopus** [comment]
Solved, wrong font name!

```
font:
  normal:
    family: Monaspace Argon Medium
    style: Regular
  bold:
    family: Monaspace Argon Medium
    style: Bold
  italic:
    family: Monaspace Radon Wide Medium
    style: Italic
  bold_italic:
    family: Monaspace Radon Wide Medium
    style: Italic

  size: 14.0
```
