### ISSUE TITLE
Mix & Match in VS Code?

### ISSUE THREAD

**Issue by marvinruder** [githubnext/monaspace#6]
I really like the examples shown in the Mix & Match section, using different font families for comments, Copilot suggestions etc.:

![](https://user-images.githubusercontent.com/18495294/281893132-1fc3f5bb-e4d5-4902-8a49-7b614dcc3d05.png)

As I understand it from https://github.com/Microsoft/vscode/issues/36512, this is not yet reproducable in VS Code. Are there any plans to support that soon, perhaps via plug-in or by discussing support with the VS Code maintainers directly?

**Comment by kcoderhtml** [comment]
I was looking for this too. Great project!

**Comment by 1eldiego** [comment]
I'm achieving exactly this with the [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) plugin.

**Comment by Bosphoramus** [comment]
I was also looking for this!

**Comment by marvinruder** [comment]
> I'm achieving exactly this with the [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) plugin.

Yes, I also tried this and got some of it working, but found it difficult to distinguish between line and block comments. Overall this would require very hacky solutions. `textMateRules` is much better suited for this purpose.

**Comment by kcoderhtml** [comment]
Current settings with custom css and js loader plugin:
```css
.mtk7 {
        font-family: "Monaspace Radon Var";
        font-weight: 500;
}

.mtk11 {
        font-family: "Monaspace Radon Var";
        font-weight: 500;
}

.mtk4 {
	font-family: "Monaspace Radon Var";
	font-weight: 500;
}

.ghost-text-decoration {
	font-family: 'Monaspace Krypton Var';
	font-weight: 200;
}

.ghost-text-decoration-preview {
	font-family: 'Monaspace Krypton Var';
	font-weight: 200;
}
```

**Comment by marvinruder** [comment]
> Current settings with custom css and js loader plugin:
> 
> ```css
> .mtk7 {
>         font-family: "Monaspace Radon Var";
>         font-weight: 500;
> }
> 
> .mtk11 {
>         font-family: "Monaspace Radon Var";
>         font-weight: 500;
> }
> 
> .mtk4 {
> 	font-family: "Monaspace Radon Var";
> 	font-weight: 500;
> }
> 
> .ghost-text-decoration {
> 	font-family: 'Monaspace Krypton Var';
> 	font-weight: 200;
> }
> 
> .ghost-text-decoration-preview {
> 	font-family: 'Monaspace Krypton Var';
> 	font-weight: 200;
> }
> ```

Nice one! I figured out something similar in the meantime as well. In short: 

If you define a custom color for a `textMate` scope (e.g. `comment.block.documentation`, `comment.line`), it will be assigned a separate `.mtk…` class (the numbers will vary, even per theme, my light theme results in different ones than my dark theme). You can grab the class name using developer tools and then create your own CSS for the aforementioned plugin. `@media (prefers-color-scheme: dark / light) { … }` will also work if you use system-wide light / dark mode to switch between themes so you can easily maintain class definitions for one dark and one light theme. 

This is still very hacky, so I hope that we will native support using the `textMateRules` setting soon. I played around a little in the VS Code codebase and found that the two main difficulties will be extending the external package [vscode-textmate](https://github.com/microsoft/vscode-textmate) and moving away from bitwise-encoding all styles in a `number`, as explained here:
https://github.com/microsoft/vscode/blob/6f2f46ec25c134595c7cb8399219d9b59794a526/src/vs/editor/common/encodedTokenAttributes.ts#L45-L66

**Comment by EliteMasterEric** [comment]
> Current settings with custom css and js loader plugin:
> 
> ```css
> .mtk7 {
>         font-family: "Monaspace Radon Var";
>         font-weight: 500;
> }
> 
> .mtk11 {
>         font-family: "Monaspace Radon Var";
>         font-weight: 500;
> }
> 
> .mtk4 {
> 	font-family: "Monaspace Radon Var";
> 	font-weight: 500;
> }
> 
> .ghost-text-decoration {
> 	font-family: 'Monaspace Krypton Var';
> 	font-weight: 200;
> }
> 
> .ghost-text-decoration-preview {
> 	font-family: 'Monaspace Krypton Var';
> 	font-weight: 200;
> }
> ```

I tested this myself and found it assigned the wrong fonts to the wrong things.

Disabling for now until someone figures out a proper solution (I'd be fine with a dedicated VSCode plugin for Monaspace if that's necessary)

**Comment by kcoderhtml** [comment]
What VS Code version do you have? I'm using the latest version for mac, 1.84.2 (Universal)
commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e. The classes seem to change between versions, so that might be the issue.  

Here is what it looks like on my end:
![screely editor](https://github.com/githubnext/monaspace/assets/92754843/7784dea6-e25f-4844-a3ff-b262875c4576)

**Comment by EliteMasterEric** [comment]
I'm on `1.84.0`.

If these classes change with every minor version, I'm going to hold off until it's properly fixed.

**Comment by kcoderhtml** [comment]
minor tweak; the styles for comments should only be mtk4:
```css
/* Comment Class */
.mtk4 {
	font-family: "Monaspace Radon Var";
	font-weight: 500;
}

/* Copilot Classes */
.ghost-text-decoration {
	font-family: 'Monaspace Krypton Var';
	font-weight: 200;
}

.ghost-text-decoration-preview {
	font-family: 'Monaspace Krypton Var';
	font-weight: 200;
}
```
